-- Consultas READ COMMITTED: 

-- TRANSACCION 1 (T1):
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


-- TRANSACCION 1 (T2):
UPDATE CUENTAS
SET SALDO = SALDO + 1000000
WHERE NUM_CUENTA = '1002';


-- TRANSACCION 1 (T3):
INSERT INTO OPERACIONESCUENTA (ID, TIPO_OPERACION_CUENTA, NUM_CUENTA, OPERACION_BANCARIA)
VALUES (20006, 'CONSIGNACION', 1002, 10004);


-- TRANSACCION 1 (T4):
UPDATE CUENTAS
SET SALDO = SALDO - 50000
WHERE NUM_CUENTA = '1004';


-- TRANSACCION 2 (T4):
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


-- Transaccion 1 (t5):
INSERT INTO OPERACIONESCUENTA (ID, TIPO_OPERACION_CUENTA, NUM_CUENTA, OPERACION_BANCARIA)
VALUES (20007, 'RETIRO', 1004, 10002);


-- Transaccion 2 (t6):
UPDATE CUENTAS
SET SALDO = SALDO - 30000
WHERE NUM_CUENTA = '1002';


-- Transaccion 1 (t7):
COMMIT;


-- Transacción 2 (t8):
INSERT INTO OPERACIONESCUENTA (ID, TIPO_OPERACION_CUENTA, NUM_CUENTA, OPERACION_BANCARIA)
VALUES (20008, 'RETIRO', 1002, 10004);


-- Transaccion 2 (t9):
UPDATE CUENTAS
SET SALDO = SALDO + 5000
WHERE NUM_CUENTA = '1004';


-- Transaccion 2 (t10):
INSERT INTO OPERACIONESCUENTA (ID, TIPO_OPERACION_CUENTA, NUM_CUENTA, OPERACION_BANCARIA)
VALUES (20009, 'CONSIGNACION', 1004, 10002);


-- Transaccion 1 (t11):
SELECT SALDO FROM CUENTAS
WHERE NUM_CUENTA = '1002';

SELECT SALDO FROM CUENTAS
WHERE NUM_CUENTA = '1004';


-- Transaccion 2 (t12):
COMMIT;


-- Transaccion 1 (t13):
SELECT SALDO FROM CUENTAS
WHERE NUM_CUENTA = '1002';

SELECT SALDO FROM CUENTAS
WHERE NUM_CUENTA = '1004';


-- Transaccion 2 (t13):
SELECT SALDO FROM CUENTAS
WHERE NUM_CUENTA = '1002';

SELECT SALDO FROM CUENTAS
WHERE NUM_CUENTA = '1004';






-- Consultas SERIALIZABLE:
-- TRANSACCION 1 (T1):
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;


-- TRANSACCION 1 (T2):
UPDATE CUENTAS
SET SALDO = SALDO + 1000000
WHERE NUM_CUENTA = '1001';


-- TRANSACCION 1 (T3):
INSERT INTO OPERACIONESCUENTA (ID, TIPO_OPERACION_CUENTA, NUM_CUENTA, OPERACION_BANCARIA)
VALUES (20015, 'CONSIGNACION', 1001, 10004);


-- TRANSACCION 1 (T4):
UPDATE CUENTAS
SET SALDO = SALDO - 50000
WHERE NUM_CUENTA = '1003';


-- TRANSACCION 2 (T4):
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;


-- Transaccion 1 (t5):
INSERT INTO OPERACIONESCUENTA (ID, TIPO_OPERACION_CUENTA, NUM_CUENTA, OPERACION_BANCARIA)
VALUES (20005, 'RETIRO', 1003, 10005);


-- Transaccion 2 (t6):
UPDATE CUENTAS
SET SALDO = SALDO - 30000
WHERE NUM_CUENTA = '1001';


-- Transaccion 1 (t7):
COMMIT;


-- Transacción 2 (t8):
INSERT INTO OPERACIONESCUENTA (ID, TIPO_OPERACION_CUENTA, NUM_CUENTA, OPERACION_BANCARIA)
VALUES (20010, 'RETIRO', 1001, 10002);


-- Transaccion 2 (t9):
UPDATE CUENTAS
SET SALDO = SALDO + 5000
WHERE NUM_CUENTA = '1003';


-- Transaccion 2 (t10):
INSERT INTO OPERACIONESCUENTA (ID, TIPO_OPERACION_CUENTA, NUM_CUENTA, OPERACION_BANCARIA)
VALUES (20011, 'CONSIGNACION', 1003, 10003);


-- Transaccion 1 (t11):
SELECT SALDO FROM CUENTAS
WHERE NUM_CUENTA = '1001';

SELECT SALDO FROM CUENTAS
WHERE NUM_CUENTA = '1003';


-- Transaccion 2 (t12):
COMMIT;



-- Transaccion 1 (t13):
SELECT SALDO FROM CUENTAS
WHERE NUM_CUENTA = '1001';

SELECT SALDO FROM CUENTAS
WHERE NUM_CUENTA = '1003';


-- Transaccion 2 (t13):
SELECT SALDO FROM CUENTAS
WHERE NUM_CUENTA = '1001';

SELECT SALDO FROM CUENTAS
WHERE NUM_CUENTA = '1003';
